GitHub Actions: NodeJS CI Pipeline Workflow
flashbots/ethers-provider-flashbots-bundle pull request #9
Opened 2021-01-05 14:21 UTC by sambacha

This PR closes #3 

Signed-off-by: sam <sam@freighttrust.com>

2021-01-05 18:51 UTC, epheph commented
@thegostep i haven't used actions before, this look good to you?

2021-01-05 19:02 UTC, thegostep requested changes
thanks for the pr 👍 

Let's test against other node versions.

Adding testing will require setting up secrets which I can handle in a separate issue.

2021-01-09 01:09 UTC, sambacha commented on .github/workflows/nodejs.yml
> +        node-version: ['12.x']
Added 10, 12, and 14 for the CI Pipeline. 

Note: I did not add cache to this workflow as the different versions for NodeJS may produce different `node_modules` dependencies, which can be done by adding each version as a separate job. I figured to keep this workflow rather simple for now.

2021-01-09 01:10 UTC, thegostep approved these changes

2021-01-09 01:10 UTC, merged

2021-01-09 01:12 UTC, sambacha commented
💯 - If yall have any sort of developer styling preferences (e.g. Angular style git commits, etc), just let me know! 

Have a great weekend,

Sam